#!/usr/bin/env sh

export FAUNADB_JAR="/faunadb/enterprise/lib/faunadb.jar"

#created by entrypoint script
config_file="/faunadb/enterprise/.config_file"
if [ -f "$config_file" ]; then
  export FAUNADB_CONFIG=$(cat "$config_file")
fi

/faunadb/enterprise/bin/faunadb-admin "$@"
